/**
 * Build script for the self-contained ESM bundle.
 *
 * 1. Locates wasmoon's `glue.wasm` in Deno's npm cache
 * 2. Base64-encodes it into a data URI
 * 3. Generates `browser/wasm_inline.ts` with the URI
 * 4. Runs `deno bundle` for both full and minified outputs
 * 5. Cleans up the generated file
 */

const decoder = new TextDecoder();

function getDenoDir(): string {
    const envDir = Deno.env.get('DENO_DIR');
    if (envDir) return envDir;

    const home = Deno.env.get('HOME') || Deno.env.get('USERPROFILE') || '';
    if (Deno.build.os === 'windows') {
        const localAppData = Deno.env.get('LOCALAPPDATA') || `${home}\\AppData\\Local`;
        return `${localAppData}\\deno`;
    }
    return `${home}/.cache/deno`;
}

async function findWasmoonWasm(): Promise<string> {
    const denoDir = getDenoDir();
    const registryPath = `${denoDir}/npm/registry.npmjs.org`;

    // Scan for wasmoon versions
    for await (const entry of Deno.readDir(registryPath)) {
        if (entry.isDirectory && entry.name.startsWith('wasmoon')) {
            const versionDir = `${registryPath}/${entry.name}`;
            for await (const ver of Deno.readDir(versionDir)) {
                if (ver.isDirectory) {
                    const candidate = `${versionDir}/${ver.name}/dist/glue.wasm`;
                    try {
                        const stat = await Deno.stat(candidate);
                        if (stat.isFile) return candidate;
                    } catch {
                        // not this one
                    }
                }
            }
        }
    }

    // Fallback: try the exact version path
    const exactPath = `${registryPath}/wasmoon/1.16.0/dist/glue.wasm`;
    try {
        const stat = await Deno.stat(exactPath);
        if (stat.isFile) return exactPath;
    } catch {
        // fall through
    }

    throw new Error(
        'Could not find wasmoon glue.wasm in Deno npm cache.\n' +
        'Run `deno cache --reload npm:wasmoon@1.16.0` first.',
    );
}

async function base64EncodeFile(path: string): Promise<string> {
    const bytes = await Deno.readFile(path);
    // Chunked conversion to avoid argument spread limit
    const chunkSize = 8192;
    let binary = '';
    for (let i = 0; i < bytes.length; i += chunkSize) {
        const chunk = bytes.slice(i, i + chunkSize);
        binary += String.fromCharCode(...chunk);
    }
    return btoa(binary);
}

async function main() {
    const repoRootUrl = new URL('..', import.meta.url);
    const repoRoot = Deno.build.os === 'windows'
        ? repoRootUrl.pathname.slice(1) // strip leading /
        : repoRootUrl.pathname;
    const distDir = `${repoRoot}dist`;
    const browserDir = `${repoRoot}browser`;
    const wasmInlineFile = `${browserDir}/wasm_inline.ts`;

    console.log('🔍 Locating wasmoon WASM binary...');
    const wasmPath = await findWasmoonWasm();
    console.log(`  Found: ${wasmPath}`);

    console.log('📦 Base64-encoding WASM...');
    const base64 = await base64EncodeFile(wasmPath);
    const dataUri = `data:application/octet-stream;base64,${base64}`;
    console.log(`  Data URI length: ${dataUri.length} chars`);

    console.log('✏️  Generating wasm_inline.ts...');
    await Deno.writeTextFile(wasmInlineFile, `// Auto-generated by scripts/build_bundle.ts — DO NOT EDIT
export const WASM_URI: string = ${JSON.stringify(dataUri)};
`);

    try {
        // Bundle full version
        console.log('📦 Bundling (full)...');
        const fullCmd = new Deno.Command('deno', {
            args: [
                'bundle',
                '--platform=browser',
                '--format=esm',
                `${browserDir}/entry.ts`,
                '-o', `${distDir}/webluabridge.bundle.js`,
            ],
            cwd: repoRoot,
            stdout: 'inherit',
            stderr: 'inherit',
        });
        const fullResult = await fullCmd.output();
        if (!fullResult.success) {
            throw new Error('deno bundle (full) failed');
        }

        // Bundle minified version
        console.log('📦 Bundling (minified)...');
        const minCmd = new Deno.Command('deno', {
            args: [
                'bundle',
                '--platform=browser',
                '--format=esm',
                '--minify',
                `${browserDir}/entry.ts`,
                '-o', `${distDir}/webluabridge.bundle.min.js`,
            ],
            cwd: repoRoot,
            stdout: 'inherit',
            stderr: 'inherit',
        });
        const minResult = await minCmd.output();
        if (!minResult.success) {
            throw new Error('deno bundle (minified) failed');
        }

        // Verify bundle sizes
        const fullStat = await Deno.stat(`${distDir}/webluabridge.bundle.js`);
        const minStat = await Deno.stat(`${distDir}/webluabridge.bundle.min.js`);
        console.log(`✅ Bundle sizes:`);
        console.log(`   webluabridge.bundle.js       ${(fullStat.size / 1024).toFixed(1)} KB`);
        console.log(`   webluabridge.bundle.min.js   ${(minStat.size / 1024).toFixed(1)} KB`);
    } finally {
        // Clean up generated file
        try {
            await Deno.remove(wasmInlineFile);
        } catch {
            // ignore
        }
        console.log('🧹 Cleaned up generated files');
    }
}

if (import.meta.main) {
    await main();
}
